name: cat_breeds_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  dio: ^5.7.0
  envied: ^1.0.0
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  get_it: ^8.0.2
  icons_launcher: ^3.0.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  envied_generator: ^1.0.0
  build_runner: ^2.4.13
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/

icons_launcher:
  image_path: "assets/images/icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
